# -*- coding: utf-8 -*-
"""TD1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I4jn4TROKvGg63o8D1R0t08tqVNW5H5v
"""

# Commented out IPython magic to ensure Python compatibility.
try:
#   %tensorflow_version 2.x
except Exception:
  pass

from __future__ import absolute_import, division,  print_function, unicode_literals
import tensorflow as tf
from tensorflow import keras

import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

data = keras.datasets.cifar10
cifar10_data = data.load_data()

#test of the data
print(type(cifar10_data))
print(len(cifar10_data))

( train_images , train_labels ) ,( test_images , test_labels ) = cifar10_data

print ( train_images [0])
print ( train_images [0]. shape )

class_names = [ 'airplane'  , 'automobile' , 'bird' , 'cat' , 'deer'
, 'dog' , 'frog' , 'horse' , 'ship' , 'truck']

#plot d'une image
plt . figure ()
plt . imshow ( train_images [ 8 ])
plt . colorbar ()
plt . grid ( False )
plt . show ()
train_labels [8]

plt.subplots(5,5)
for i in range (25):
  plt . imshow (train_images [i])
  plt . xlabel (train_labels[i])

