# -*- coding: utf-8 -*-
"""TD9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wrnEGyoUcqLb4om-niJe-6uEr6Lanroa
"""

# Commented out IPython magic to ensure Python compatibility.
try:
#   %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf
from tensorflow import keras
import pandas as pd
import io
from google.colab import files
import numpy as np

import pandas as pd 
import io

from google.colab import files

uploaded = files.upload()

data = pd.read_csv('data.csv', sep=',')

data.head()

yahoo = data[data["symbol"] == "YHOO"]
yahoo_stock_price = yahoo.iloc[:,[1,5]]
yahoo_stock_price.head()

print (len(yahoo_stock_price))

print(type(yahoo_stock_price))

test=yahoo_stock_price.values

n_train = 1409

train_yahoo, test_yahoo = test[:n_train, :] , test[n_train:, :]

